### ISSUE TITLE
pyperclip 동작 이상

### ISSUE THREAD

**Issue by tyhan** [jybaek/translate-in-terminal#2]
docker 로 실행시 pyperclip 정상 동작 하지 않음.
회피 루틴이 필요.

```
Traceback (most recent call last):
  File "/usr/bin/translate", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/translate/translate.py", line 24, in main
    text = [pyperclip.paste()]
  File "/usr/lib/python3.6/site-packages/pyperclip/__init__.py", line 638, in lazy_load_stub_paste
    return paste()
  File "/usr/lib/python3.6/site-packages/pyperclip/__init__.py", line 301, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error 
```

**Comment by jybaek** [comment]
Any way, `pyperclip.PyperclipException` This should be an exception for this part. 

e.g)
```python
try:
    ...
except pyperclip.PyperclipException:
    ...
```
Thank you :)

**Comment by RavenKyu** [comment]
Anyway, This problem is heavy issue to me. I didn't know that pyperclip is not working on docker services. Some of modules I wrote in work, using pyperclip a lot. 

I think working not on GUI environment is one of reason? I should check it. thx.

**Comment by RavenKyu** [comment]
according to the error message, if there is no mechanisms of handling mouse. Working on shell in docker is not able to handle mouse. It's required to install one of the copy/paste mechanisms.

```bash
sudo apt-get install xsel to install the xsel utility.
sudo apt-get install xclip to install the xclip utility.
pip install gtk to install the gtk Python module.
pip install PyQt4 to install the PyQt4 Python module.
```
The goal of this program is to translate. Using clipboard is one of ability in the program.
So, we should test before using clipboard, If user try to use clipboard  we catch `pyperclip.PyperclipException` and then we just print the notice.

**Comment by RavenKyu** [comment]
![image](https://user-images.githubusercontent.com/1933975/52513284-29fc1100-2c4d-11e9-9c0d-c483f2237aca.png)

README.md 및 도움말 명령어 출력 변경

**Comment by tyhan** [comment]
There are version issues. It is an issue that only happens on the docker.

```
$ pip3 install gtk
Collecting gtk
  Could not find a version that satisfies the requirement gtk (from versions: )
No matching distribution found for gtk
```
